/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;


import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import ru.bsuedu.cad.lab.app.OrderClient;
import ru.bsuedu.cad.lab.app.TableConfiguration;

public class App {
    
    public static void main(String[] args) {
        
        ApplicationContext context = new AnnotationConfigApplicationContext(TableConfiguration.class);
        var client = context.getBean(OrderClient.class);
        client.run();
        
    }
}
